apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod-1
    labels:
      app: nginx
      env: dev
spec:
   containers:
   - name: nginx-cont-1
     image: nginx
     ports:
     - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: nginx-svc
spec:
  type: ClusterIP  ### This is default
  selector:
     app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
